### ISSUE TITLE
Debug Messages Appearing In Chat

### ISSUE THREAD

**Issue by iBELLinc** [nsgwick/FlintAndAnimals#2]
The current (and previous version) of this plugin are currently spamming text chat in-game every time that you right click any entity. This is not only for OPs but also for normal players on the server. This is the exact message that is being displayed on screen:

Item fetched.
Type fetched.
Item fetched.
Type fetched.

As a side note: It was extremely time consuming to locate the problem plugin since these debug messages are not tagged with anything and this isn't resulting in a crash. Would it be possible to provide some sort of indicator on the message to identify it origins?

For example:
[F&A] Item fetched.
[F&A] Type fetched.
[F&A] Item fetched.
[F&A] Type fetched.

**Comment by Nicholamsious** [comment]
Hi, thanks for submitting this issue!
This plugin definitely isn't causing your console spam problem. I would check with the other developers of your other plugins to resolve this issue or test each of your plugins themselves to narrow down your focus.
However, I've taken your thoughts into account because I had not included the console prefix for command feedback. This change makes sense because people can easily become confused as to which messages originate from which plugins.
I have released version 1.1 of FlintAndAnimals which includes this.

**Comment by iBELLinc** [comment]
Hey, thanks for getting back to me! I appreciate you taking my suggestion into account. Also, I can confirm that the new version of the plugin does not cause in-game chat spam. Thanks again :)
